### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #1

### ISSUE THREAD

**Issue by boguz** [survivingwithandroid/Swa-app#4]
I have been trying to follow your tutorial, but when i try to run the app (also after importing your files from gitHub) i always get this error message.
Any idea what it mean? How could we fix it?    

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
Process: com.anatis.ueder, PID: 29363
java.lang.RuntimeException: An error occured while executing doInBackground()
  at android.os.AsyncTask$3.done(AsyncTask.java:304)
  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
  at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
  at org.json.JSONTokener.nextValue(JSONTokener.java:94)
  at org.json.JSONObject.<init>(JSONObject.java:156)
  at org.json.JSONObject.<init>(JSONObject.java:173)
  at com.anatis.ueder.JSONWeatherParser.getWeather(JSONWeatherParser.java:17)
  at com.anatis.ueder.MainActivity$JSONWeatherTask.doInBackground(MainActivity.java:63)
  at com.anatis.ueder.MainActivity$JSONWeatherTask.doInBackground(MainActivity.java:55)
  at android.os.AsyncTask$2.call(AsyncTask.java:292)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
  at java.lang.Thread.run(Thread.java:818)
```

**Comment by Andrew2100** [comment]
I have the same issue, any ideas?

**Comment by vivster13** [comment]
i too am having this issue

**Comment by canberkcakmak** [comment]
In WeatherHttpClient class you will add this lines under this line `private static String BASE_URL`

`private static String LAST = "&APPID=XXXXXXXXX"` you have to get appid in openweathermap.org and add app id to xxxx.

Then you have to change this line = `con=(HttpURLConnection)(new URL(BASE_URL+location+LAST))` add LAST to this line and it will be work.
